// File generated from our OpenAPI spec by Stainless.

package com.growsurf.api.models.campaign

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.growsurf.api.core.JsonValue
import com.growsurf.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CampaignListResponseTest {

    @Test
    fun create() {
        val campaignListResponse =
            CampaignListResponse.builder()
                .addCampaign(
                    Campaign.builder()
                        .id("id")
                        .impressionCount(0L)
                        .inviteCount(0L)
                        .name("name")
                        .participantCount(0L)
                        .referralCount(0L)
                        .addReward(
                            Campaign.Reward.builder()
                                .id("id")
                                .isUnlimited(true)
                                .metadata(
                                    Campaign.Reward.Metadata.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .type(Campaign.Reward.Type.SINGLE_SIDED)
                                .commissionStructure(
                                    CommissionStructure.builder()
                                        .amount(0L)
                                        .approvalRequired(true)
                                        .duration("duration")
                                        .durationInMonths(0L)
                                        .event("event")
                                        .hasIntro(true)
                                        .hasMaxAmount(true)
                                        .holdDuration(0L)
                                        .introAmount(0L)
                                        .introAmountIso("introAmountISO")
                                        .introDuration("introDuration")
                                        .introDurationInMonths(0L)
                                        .introPercent(0.0)
                                        .introType("introType")
                                        .maxAmount(0L)
                                        .maxAmountIso("maxAmountISO")
                                        .minPaidReferrals(0L)
                                        .percent(0.0)
                                        .type(CommissionStructure.Type.PERCENT)
                                        .build()
                                )
                                .conversionsRequired(0L)
                                .couponCode("couponCode")
                                .description("description")
                                .imageUrl("imageUrl")
                                .limit(0L)
                                .limitDuration(Campaign.Reward.LimitDuration.IN_TOTAL)
                                .nextMilestonePrefix("nextMilestonePrefix")
                                .nextMilestoneSuffix("nextMilestoneSuffix")
                                .numberOfWinners(0L)
                                .order(0L)
                                .referralDescription("referralDescription")
                                .referredRewardUpfront(true)
                                .build()
                        )
                        .status(Campaign.Status.DRAFT)
                        .type(Campaign.Type.REFERRAL)
                        .winnerCount(0L)
                        .currencyIso("xxx")
                        .build()
                )
                .build()

        assertThat(campaignListResponse.campaigns())
            .containsExactly(
                Campaign.builder()
                    .id("id")
                    .impressionCount(0L)
                    .inviteCount(0L)
                    .name("name")
                    .participantCount(0L)
                    .referralCount(0L)
                    .addReward(
                        Campaign.Reward.builder()
                            .id("id")
                            .isUnlimited(true)
                            .metadata(
                                Campaign.Reward.Metadata.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .type(Campaign.Reward.Type.SINGLE_SIDED)
                            .commissionStructure(
                                CommissionStructure.builder()
                                    .amount(0L)
                                    .approvalRequired(true)
                                    .duration("duration")
                                    .durationInMonths(0L)
                                    .event("event")
                                    .hasIntro(true)
                                    .hasMaxAmount(true)
                                    .holdDuration(0L)
                                    .introAmount(0L)
                                    .introAmountIso("introAmountISO")
                                    .introDuration("introDuration")
                                    .introDurationInMonths(0L)
                                    .introPercent(0.0)
                                    .introType("introType")
                                    .maxAmount(0L)
                                    .maxAmountIso("maxAmountISO")
                                    .minPaidReferrals(0L)
                                    .percent(0.0)
                                    .type(CommissionStructure.Type.PERCENT)
                                    .build()
                            )
                            .conversionsRequired(0L)
                            .couponCode("couponCode")
                            .description("description")
                            .imageUrl("imageUrl")
                            .limit(0L)
                            .limitDuration(Campaign.Reward.LimitDuration.IN_TOTAL)
                            .nextMilestonePrefix("nextMilestonePrefix")
                            .nextMilestoneSuffix("nextMilestoneSuffix")
                            .numberOfWinners(0L)
                            .order(0L)
                            .referralDescription("referralDescription")
                            .referredRewardUpfront(true)
                            .build()
                    )
                    .status(Campaign.Status.DRAFT)
                    .type(Campaign.Type.REFERRAL)
                    .winnerCount(0L)
                    .currencyIso("xxx")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val campaignListResponse =
            CampaignListResponse.builder()
                .addCampaign(
                    Campaign.builder()
                        .id("id")
                        .impressionCount(0L)
                        .inviteCount(0L)
                        .name("name")
                        .participantCount(0L)
                        .referralCount(0L)
                        .addReward(
                            Campaign.Reward.builder()
                                .id("id")
                                .isUnlimited(true)
                                .metadata(
                                    Campaign.Reward.Metadata.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .type(Campaign.Reward.Type.SINGLE_SIDED)
                                .commissionStructure(
                                    CommissionStructure.builder()
                                        .amount(0L)
                                        .approvalRequired(true)
                                        .duration("duration")
                                        .durationInMonths(0L)
                                        .event("event")
                                        .hasIntro(true)
                                        .hasMaxAmount(true)
                                        .holdDuration(0L)
                                        .introAmount(0L)
                                        .introAmountIso("introAmountISO")
                                        .introDuration("introDuration")
                                        .introDurationInMonths(0L)
                                        .introPercent(0.0)
                                        .introType("introType")
                                        .maxAmount(0L)
                                        .maxAmountIso("maxAmountISO")
                                        .minPaidReferrals(0L)
                                        .percent(0.0)
                                        .type(CommissionStructure.Type.PERCENT)
                                        .build()
                                )
                                .conversionsRequired(0L)
                                .couponCode("couponCode")
                                .description("description")
                                .imageUrl("imageUrl")
                                .limit(0L)
                                .limitDuration(Campaign.Reward.LimitDuration.IN_TOTAL)
                                .nextMilestonePrefix("nextMilestonePrefix")
                                .nextMilestoneSuffix("nextMilestoneSuffix")
                                .numberOfWinners(0L)
                                .order(0L)
                                .referralDescription("referralDescription")
                                .referredRewardUpfront(true)
                                .build()
                        )
                        .status(Campaign.Status.DRAFT)
                        .type(Campaign.Type.REFERRAL)
                        .winnerCount(0L)
                        .currencyIso("xxx")
                        .build()
                )
                .build()

        val roundtrippedCampaignListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(campaignListResponse),
                jacksonTypeRef<CampaignListResponse>(),
            )

        assertThat(roundtrippedCampaignListResponse).isEqualTo(campaignListResponse)
    }
}
