// File generated from our OpenAPI spec by Stainless.

package com.growsurf.api.models.campaign

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.growsurf.api.core.JsonValue
import com.growsurf.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CampaignTest {

    @Test
    fun create() {
        val campaign =
            Campaign.builder()
                .id("id")
                .impressionCount(0L)
                .inviteCount(0L)
                .name("name")
                .participantCount(0L)
                .referralCount(0L)
                .addReward(
                    Campaign.Reward.builder()
                        .id("id")
                        .isUnlimited(true)
                        .metadata(
                            Campaign.Reward.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .type(Campaign.Reward.Type.SINGLE_SIDED)
                        .commissionStructure(
                            CommissionStructure.builder()
                                .amount(0L)
                                .approvalRequired(true)
                                .duration("duration")
                                .durationInMonths(0L)
                                .event("event")
                                .hasIntro(true)
                                .hasMaxAmount(true)
                                .holdDuration(0L)
                                .introAmount(0L)
                                .introAmountIso("introAmountISO")
                                .introDuration("introDuration")
                                .introDurationInMonths(0L)
                                .introPercent(0.0)
                                .introType("introType")
                                .maxAmount(0L)
                                .maxAmountIso("maxAmountISO")
                                .minPaidReferrals(0L)
                                .percent(0.0)
                                .type(CommissionStructure.Type.PERCENT)
                                .build()
                        )
                        .conversionsRequired(0L)
                        .couponCode("couponCode")
                        .description("description")
                        .imageUrl("imageUrl")
                        .limit(0L)
                        .limitDuration(Campaign.Reward.LimitDuration.IN_TOTAL)
                        .nextMilestonePrefix("nextMilestonePrefix")
                        .nextMilestoneSuffix("nextMilestoneSuffix")
                        .numberOfWinners(0L)
                        .order(0L)
                        .referralDescription("referralDescription")
                        .referredRewardUpfront(true)
                        .build()
                )
                .status(Campaign.Status.DRAFT)
                .type(Campaign.Type.REFERRAL)
                .winnerCount(0L)
                .currencyIso("xxx")
                .build()

        assertThat(campaign.id()).isEqualTo("id")
        assertThat(campaign.impressionCount()).isEqualTo(0L)
        assertThat(campaign.inviteCount()).isEqualTo(0L)
        assertThat(campaign.name()).isEqualTo("name")
        assertThat(campaign.participantCount()).isEqualTo(0L)
        assertThat(campaign.referralCount()).isEqualTo(0L)
        assertThat(campaign.rewards())
            .containsExactly(
                Campaign.Reward.builder()
                    .id("id")
                    .isUnlimited(true)
                    .metadata(
                        Campaign.Reward.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .type(Campaign.Reward.Type.SINGLE_SIDED)
                    .commissionStructure(
                        CommissionStructure.builder()
                            .amount(0L)
                            .approvalRequired(true)
                            .duration("duration")
                            .durationInMonths(0L)
                            .event("event")
                            .hasIntro(true)
                            .hasMaxAmount(true)
                            .holdDuration(0L)
                            .introAmount(0L)
                            .introAmountIso("introAmountISO")
                            .introDuration("introDuration")
                            .introDurationInMonths(0L)
                            .introPercent(0.0)
                            .introType("introType")
                            .maxAmount(0L)
                            .maxAmountIso("maxAmountISO")
                            .minPaidReferrals(0L)
                            .percent(0.0)
                            .type(CommissionStructure.Type.PERCENT)
                            .build()
                    )
                    .conversionsRequired(0L)
                    .couponCode("couponCode")
                    .description("description")
                    .imageUrl("imageUrl")
                    .limit(0L)
                    .limitDuration(Campaign.Reward.LimitDuration.IN_TOTAL)
                    .nextMilestonePrefix("nextMilestonePrefix")
                    .nextMilestoneSuffix("nextMilestoneSuffix")
                    .numberOfWinners(0L)
                    .order(0L)
                    .referralDescription("referralDescription")
                    .referredRewardUpfront(true)
                    .build()
            )
        assertThat(campaign.status()).isEqualTo(Campaign.Status.DRAFT)
        assertThat(campaign.type()).isEqualTo(Campaign.Type.REFERRAL)
        assertThat(campaign.winnerCount()).isEqualTo(0L)
        assertThat(campaign.currencyIso()).contains("xxx")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val campaign =
            Campaign.builder()
                .id("id")
                .impressionCount(0L)
                .inviteCount(0L)
                .name("name")
                .participantCount(0L)
                .referralCount(0L)
                .addReward(
                    Campaign.Reward.builder()
                        .id("id")
                        .isUnlimited(true)
                        .metadata(
                            Campaign.Reward.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .type(Campaign.Reward.Type.SINGLE_SIDED)
                        .commissionStructure(
                            CommissionStructure.builder()
                                .amount(0L)
                                .approvalRequired(true)
                                .duration("duration")
                                .durationInMonths(0L)
                                .event("event")
                                .hasIntro(true)
                                .hasMaxAmount(true)
                                .holdDuration(0L)
                                .introAmount(0L)
                                .introAmountIso("introAmountISO")
                                .introDuration("introDuration")
                                .introDurationInMonths(0L)
                                .introPercent(0.0)
                                .introType("introType")
                                .maxAmount(0L)
                                .maxAmountIso("maxAmountISO")
                                .minPaidReferrals(0L)
                                .percent(0.0)
                                .type(CommissionStructure.Type.PERCENT)
                                .build()
                        )
                        .conversionsRequired(0L)
                        .couponCode("couponCode")
                        .description("description")
                        .imageUrl("imageUrl")
                        .limit(0L)
                        .limitDuration(Campaign.Reward.LimitDuration.IN_TOTAL)
                        .nextMilestonePrefix("nextMilestonePrefix")
                        .nextMilestoneSuffix("nextMilestoneSuffix")
                        .numberOfWinners(0L)
                        .order(0L)
                        .referralDescription("referralDescription")
                        .referredRewardUpfront(true)
                        .build()
                )
                .status(Campaign.Status.DRAFT)
                .type(Campaign.Type.REFERRAL)
                .winnerCount(0L)
                .currencyIso("xxx")
                .build()

        val roundtrippedCampaign =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(campaign),
                jacksonTypeRef<Campaign>(),
            )

        assertThat(roundtrippedCampaign).isEqualTo(campaign)
    }
}
